package constants

const (
	BufferInitialLines     = 20000
	BufferInitialEntries   = 30000
	DefaultFilteredIP      = "0.0.0.0"
	DefaultUnixHostFile    = "/etc/hosts"
	DefaultWindowsHostFile = `%windir%\System32\drivers\etc\hosts`
	StartMarker            = "### this content was generated by hosts-filter, please leave this line intact ###"
	EndMarker              = "### end of hosts-filter content, please leave this line intact ###"
)

var (
	IgnoreDomains = []string{
		"localhost",
		"localhost.localdomain",
		"broadcasthost",
		"local",
		"ip6-localhost",
		"ip6-loopback",
		"ip6-localnet",
		"ip6-mcastprefix",
		"ip6-allnodes",
		"ip6-allrouters",
		"ip6-allhosts",
	}
)
