project_name: hosts-filter

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - id: hostsfilter_targz
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

  - id: hostsfilter_zip
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
    goarch:
      - "386"
      - amd64

archives:
  - id: targz
    builds:
    - hostsfilter_targz
    format: tar.gz

  - id: zip
    builds:
    - hostsfilter_zip
    format: zip
    
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  -
    goos: linux
    goarch: amd64
    ids:
    - hostsfilter_targz
    image_templates:
    - "creativeprojects/hosts-filter:latest"
    - "creativeprojects/hosts-filter:{{ .RawVersion }}"
    skip_push: false
    dockerfile: build/Dockerfile
