---
lists:
  # -
  #   url: http://winhelp2002.mvps.org/hosts.txt
  # -
  #   url: http://someonewhocares.org/hosts/hosts
  # -
  #   url: http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext
  -
    url: lists/mvps.txt
  -
    url: lists/error.txt
  -
    url: http://localhost/error.txt
  -
    url: lists/pollock.txt
  -
    url: lists/lowe.txt
