name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.24']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go_version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: "go test -v -race -short -coverprofile='coverage.out' ./..."
      shell: bash

    - name: Code coverage
      run: "if [ -f coverage.out ]; then bash <(curl -s https://codecov.io/bash); fi"
      shell: bash
